name: Evolene CI

on:
  push:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '*.png'
  workflow_dispatch:

jobs:
  Evolene:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Run Evolene CI pipeline steps
        shell: bash
        env:
          SLACK_CHANNELS:  "#team-kth-webb-build"
          BUILD_INFORMATION_OUTPUT_FILE: '/config/version.js'
          EVOLENE_TEST_SECRETS: '${{secrets.EVOLENE_TEST_SECRETS}}'
        run: |
          ${{ secrets.EVOLENE_RUN_COMMAND }}
